analytics-id: null
subtitle:
  active: false
  text: 'Time is an illusion, lunchtime doubly so!!'
nav:
  pages:
    active: true
  social:
    active: true
featured-img:
  active: true
categories:
  active: true
date-under-post:
  active: true
mathjax:
  active: true
related-posts:
  active: true
  title: You May Also Enjoy
comments: true
